/**
 * Date Accountability Main Page
 * Path: /date-accountability
 * 
 * This is the main landing page for the date accountability section of the application.
 * It showcases various features and tools available to users for tracking and improving their dating experiences.
 * 
 * Components:
 * - Breadcrumb: Navigation breadcrumb
 * - Feature Cards: Grid of available date accountability features
 * 
 * Authentication:
 * - Partially protected (some features require login)
 * - Shows different UI states for logged-in vs anonymous users
 * 
 * Features Displayed:
 * 1. AI Generated Feedback (/date-accountability/generate-feedback)
 *    - Creates personalized feedback using AI
 * 
 * 2. Date Analysis (/date-accountability/date-analysis)
 *    - Provides AI-powered insights on your dates
 * 
 * 3. Personal Date Journal (/date-accountability/journal)
 *    - Allows users to maintain date records
 * 
 * 4. Date Reminders (/date-accountability/date-reminders)
 *    - Manages date notification settings
 * 
 * 5. Community Feedback (/community/feedback)
 *    - Facilitates feedback sharing and discussions
 * 
 * UI Features:
 * - Responsive grid layout (1-4 columns based on screen size)
 * - Hover animations and visual effects
 * - Dark/light mode support
 * - Call-to-action buttons for key features
 * 
 * State Management:
 * - Uses NextAuth session for authentication state
 * - Conditional rendering based on auth status
 */

import React from 'react';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { Metadata } from 'next';
import Breadcrumb from '@/components/Breadcrumb';
import Link from 'next/link';
import { 
  PenTool, 
  Heart, 
  MessageSquare, 
  Lightbulb,
  Calendar,
  Users,
  Clock,
  BookOpen,
  Brain,
  Sparkles,
  ScrollText,
  BookMarked
} from 'lucide-react';

const dateFeatures = [
  {
    title: "AI Generated Feedback",
    description: "Receive personalized feedback generated by our AI dating companion.",
    icon: Sparkles,
    color: "text-gray-300 dark:text-gray-300 light:text-black",
    bgColor: "bg-light-4 dark:bg-gray-900",
    href: "/date-accountability/generate-feedback"
  },
  {
    title: "Date Analysis",
    description: "Get thoughtful reflections and insights on your dating experiences.",
    icon: Brain,
    color: "text-gray-300 dark:text-gray-300 light:text-black",
    bgColor: "bg-light-4 dark:bg-gray-900",
    href: "/date-accountability/date-analysis"
  },
  {
    title: "Personal Date Journal",
    description: "Keep track of your dates and dating journey over time.",
    icon: PenTool,
    color: "text-gray-300 dark:text-gray-300 light:text-black",
    bgColor: "bg-light-4 dark:bg-gray-900",
    href: "/date-accountability/journal"
  },
  {
    title: "Date Reminders",
    description: "Set reminders for upcoming dates and feedback collection.",
    icon: Clock,
    color: "text-gray-300 dark:text-gray-300 light:text-black",
    bgColor: "bg-light-4 dark:bg-gray-900",
    href: "/date-accountability/date-reminders"
  },
  {
    title: "Feedback Templates",
    description: "Access various feedback templates for different dating scenarios.",
    icon: ScrollText,
    color: "text-gray-300 dark:text-gray-300 light:text-black",
    bgColor: "bg-light-4 dark:bg-gray-900",
  },
  {
    title: "Community Feedback",
    description: "Share feedback and connect with others in the dating community.",
    icon: Users,
    color: "text-gray-300 dark:text-gray-300 light:text-black",
    bgColor: "bg-light-4 dark:bg-gray-900",
  },
  {
    title: "Feedback Discussions",
    description: "Engage in meaningful discussions about dating experiences.",
    icon: MessageSquare,
    color: "text-gray-300 dark:text-gray-300 light:text-black",
    bgColor: "bg-light-4 dark:bg-gray-900",
    href: "/community/feedback"
  },
  {
    title: "Daily Dating Tips",
    description: "Receive daily tips to enhance your dating experience.",
    icon: Calendar,
    color: "text-gray-300 dark:text-gray-300 light:text-black",
    bgColor: "bg-light-4 dark:bg-gray-900",
    href: "/date-accountability/daily-tips"
  },
  {
    title: "Date Groups",
    description: "Join or create groups for collective dating support.",
    icon: Users,
    color: "text-gray-300 dark:text-gray-300 light:text-black",
    bgColor: "bg-light-4 dark:bg-gray-900",
  },
  {
    title: "Date History",
    description: "Review your dating history and track your progress.",
    icon: Clock,
    color: "text-gray-300 dark:text-gray-300 light:text-black",
    bgColor: "bg-light-4 dark:bg-gray-900",
  },
  {
    title: "Date Insights",
    description: "Gain deeper understanding through AI-powered date analysis.",
    icon: Lightbulb,
    color: "text-gray-300 dark:text-gray-300 light:text-black",
    bgColor: "bg-light-4 dark:bg-gray-900",
  },
  {
    title: "Favorite Feedback",
    description: "Save and organize your favorite feedback for easy access.",
    icon: BookMarked,
    color: "text-gray-300 dark:text-gray-300 light:text-black",
    bgColor: "bg-light-4 dark:bg-gray-900",
  }
];

export const DATE_THEMES = [
  { id: 'first-date', name: 'First Date', description: 'Guidance for planning and preparing for first dates' },
  { id: 'follow-up', name: 'Follow-up', description: 'Tips for maintaining connection after dates' },
  { id: 'feedback', name: 'Feedback', description: 'Collecting and analyzing date feedback' },
  { id: 'improvement', name: 'Improvement', description: 'Areas for personal growth in dating' },
  { id: 'communication', name: 'Communication', description: 'Enhancing communication skills' },
  { id: 'confidence', name: 'Confidence', description: 'Building confidence in dating situations' },
  { id: 'boundaries', name: 'Boundaries', description: 'Setting and maintaining healthy boundaries' },
  { id: 'reflection', name: 'Reflection', description: 'Reflecting on dating experiences' }
];

export default async function DateAccountabilityPage() {
  const session = await getServerSession(authOptions);

  return (
    <>
      <Breadcrumb pageTitle="Date Accountability" />
      <div className="container mx-auto px-4 py-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-white dark:text-white light:text-black mb-4">
            Date Accountability Dashboard
          </h1>
          <p className="text-gray-400 dark:text-gray-400 light:text-black/80">
            Track your dating journey, collect feedback, and improve your dating experiences.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {/* Date Reminders */}
          <div className="relative rounded-xl bg-[url(/images/cta/grid.svg)] p-6 border border-gray-300/20 dark:border-gray-600/20 shadow-lg transform hover:-translate-y-1 hover:shadow-xl transition-all"
            style={{
              boxShadow: 'inset -8px -8px 16px rgba(0,0,0,0.1), inset 8px 8px 16px rgba(255,255,255,0.1), 0 4px 24px rgba(0, 0, 0, 0.1)',
              transform: 'perspective(1000px) rotateX(2deg)'
            }}>
            <div className="relative z-10">
              <h2 className="text-xl font-semibold text-white mb-4">Date Reminders</h2>
              <p className="text-gray-400 mb-4">Set up reminders for before and after your dates</p>
              <Link href="/date-accountability/date-reminders" className="text-purple-400 hover:text-purple-300">
                Configure Reminders →
              </Link>
            </div>
          </div>

          {/* Date Journal */}
          <div className="relative rounded-xl bg-[url(/images/cta/grid.svg)] p-6 border border-gray-300/20 dark:border-gray-600/20 shadow-lg transform hover:-translate-y-1 hover:shadow-xl transition-all"
            style={{
              boxShadow: 'inset -8px -8px 16px rgba(0,0,0,0.1), inset 8px 8px 16px rgba(255,255,255,0.1), 0 4px 24px rgba(0, 0, 0, 0.1)',
              transform: 'perspective(1000px) rotateX(2deg)'
            }}>
            <div className="relative z-10">
              <h2 className="text-xl font-semibold text-white mb-4">Date Journal</h2>
              <p className="text-gray-400 mb-4">Record and reflect on your dating experiences</p>
              <Link href="/date-accountability/journal" className="text-purple-400 hover:text-purple-300">
                View Journal →
              </Link>
            </div>
          </div>

          {/* Date Analysis */}
          <div className="relative rounded-xl bg-[url(/images/cta/grid.svg)] p-6 border border-gray-300/20 dark:border-gray-600/20 shadow-lg transform hover:-translate-y-1 hover:shadow-xl transition-all"
            style={{
              boxShadow: 'inset -8px -8px 16px rgba(0,0,0,0.1), inset 8px 8px 16px rgba(255,255,255,0.1), 0 4px 24px rgba(0, 0, 0, 0.1)',
              transform: 'perspective(1000px) rotateX(2deg)'
            }}>
            <div className="relative z-10">
              <h2 className="text-xl font-semibold text-white mb-4">Date Analysis</h2>
              <p className="text-gray-400 mb-4">Get insights and feedback on your dating journey</p>
              <Link href="/date-accountability/analysis" className="text-purple-400 hover:text-purple-300">
                View Analysis →
              </Link>
            </div>
          </div>
        </div>

        {!session && (
          <div className="text-center mb-12">
            <Link
              href="/auth/login"
              className="button-border-gradient hover:button-gradient-hover relative inline-flex items-center gap-1.5 rounded-lg px-6 py-3 text-white dark:text-white light:text-black shadow-button hover:shadow-none"
            >
              Log In to Start Dating
              <svg
                width="16"
                height="16"
                viewBox="0 0 16 16"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
                className="dark:fill-white light:fill-black"
              >
                <path
                  d="M14.4002 7.60002L9.2252 2.35002C9.0002 2.12502 8.6502 2.12502 8.4252 2.35002C8.2002 2.57502 8.2002 2.92502 8.4252 3.15002L12.6252 7.42502H2.0002C1.7002 7.42502 1.4502 7.67502 1.4502 7.97502C1.4502 8.27502 1.7002 8.55003 2.0002 8.55003H12.6752L8.4252 12.875C8.2002 13.1 8.2002 13.45 8.4252 13.675C8.5252 13.775 8.6752 13.825 8.8252 13.825C8.9752 13.825 9.1252 13.775 9.2252 13.65L14.4002 8.40002C14.6252 8.17502 14.6252 7.82503 14.4002 7.60002Z"
                />
              </svg>
            </Link>
          </div>
        )}
      </div>
    </>
  );
} 